// <auto-generated />
namespace MyPhoneBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relate_userid_to_contacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relate_userid_to_contacts));
        
        string IMigrationMetadata.Id
        {
            get { return "201610211840042_relate_userid_to_contacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
